.\" Copyright 2010 Bernhard R. Fischer.
.\"
.\" This file is part of idefix.
.\"
.\" Idefix is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, version 3 of the License.
.\"
.\" Idefix is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with idefix. If not, see <http://www.gnu.org/licenses/>.
.\"
.TH IDEFIX 1 2010-01-29 "idefix" "Idefix User's Manual"
.SH NAME
idefix \- Idefix is a super simple and tiny multi-threaded HTTP server.
.SH SYNOPSIS
.B idefix
[\fIport\fP]
.br
.SH DESCRIPTION
Idefix is a super simple and tiny multi-threaded HTTP server. It opens a
listening TCP port at 8080 and waits for incoming connections there.  You may
specify a different \fIport\fP number as command line argument.

Currently it supports only the method GET and protocol version HTTP/0.9,
HTTP/1.0, and HTTP/1.1. The latter is not fully implemented, hence, it cannot
be considered as being HTTP/1.1 compliant. It does not support name-based
virtual hosts.

.SS OPTIONS
.TP
\fBport\fP
A port number may optionally be specified on the command line.

.SH NOTES
This man page is still not finished...

.\" .SH FILES

.SH AUTHOR
Concepts, software, and man page written by Bernhard R. Fischer.

.\" .SH "SEE ALSO"

.SH COPYRIGHT
Copyright 2010 Bernhard R. Fischer.

This file is part of idefix.

Idefix is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.

Idefix is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with idefix. If not, see <http://www.gnu.org/licenses/>.
